CREATE SEQUENCE PHARMACY_DRUG_SYNC_STG_SEQ  START WITH 1 INCREMENT BY 1 MINVALUE 1 CACHE 20 NOCYCLE NOORDER;

CREATE TABLE HOSPITAL.PHARMACY_DRUG_SYNC_STG
(
  ID                   NUMBER NOT NULL, 
  DRUG_CODE		       NVARCHAR2(255), 
  DRUG_QTY             NUMBER(10,2),
  CREATED_ON           DATE DEFAULT SYSDATE, 
  UPDATED_ON           DATE 
  )
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX PHARMACY_DRUG_SYNC_STG_PK ON PHARMACY_DRUG_SYNC_STG
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE TRIGGER PHARMACY_DRUG_SYNC_STG 
BEFORE INSERT
ON PHARMACY_DRUG_SYNC_STG 
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;

   SELECT PHARMACY_DRUG_SYNC_STG_SEQ.NEXTVAL INTO tmpVar FROM dual;
   :NEW.ID := tmpVar;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;

ALTER TABLE PHARMACY_DRUG_SYNC_STG ADD (
  CONSTRAINT PHARMACY_DRUG_SYNC_STG_PK
 PRIMARY KEY
 (ID));
 
